
root: true

parser: "babel-eslint"

extends:
  - semistandard-react
  - plugin:import/errors
  - plugin:import/warnings

env:
  browser: true
  node: true
  jest: true
  es6: true

rules:
  comma-dangle: [ "error", "always-multiline" ]
